version: '3.8'

services:
  # db service
  db:
    build:
      context: src/db
      dockerfile: Dockerfile
    image: mediawatch-postgresql-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./src/db/data:/var/lib/postgresql/data
    networks:
      - mediawatch-network
    restart: "no"

  backend:
    build: src/backend
    container_name: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./src/backend/app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    networks:
      - mediawatch-network
    restart: "no"

  frontend:
    build: src/frontend
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mediawatch-network
    restart: "no"

networks:
  mediawatch-network:
    driver: bridge

volumes:
  postgres_data:
